"datasrc_id","authors","title","year","journal","vol_city","issue_state","start_page","end_page"
"D1191 ","I.J. Tinsley, R.R. Lowry","Bromine content of lipids of marine organisms",1980,"American Oil Chemists' Society, Journal","","1","31","33"
"D3296 ","C.E. Damon, B.C. Pettitt","Sugars and Sugar Products: High Performance Liquid Chomatographic Determination of Fructose, Glucose and Sucrose in Molasses",1980,"J. AOAC","63","3","476","480"
"D3309 ","M. Horbowicz","Adaptation of the method of sugars determination by gas chromatography (GC) and characteristics of  their occurrence",1980,"Acta Alimentaria Polonica","6","4","227","236"
"D3318 ","D.A. Kline","Quantitative determination of sugars in fruits by GLC separation of TMS derivatives",1970,"Journal of AOAC International","53","6","1198","1202"
"D3321 ","C. Y. Lee","Free sugars in fruits and vegetables",1970,"Food Science and Technology","","1","",""
"D3339 ","K.W. Swallow, N.H. Low","Analysis And Quantitation Of The Carbohydrates In Honey Using High-Performance Liquid Chromatography.",1990,"Journal of Agricultural and Food Chemistry","38","9","1828","1832"
"D3357 ","V.C. Morris, O.A. Levander","Selenium content of food",1970,"Journal of Nutrition","100","12","1383","1388"
"D3358 ","A.L. Moxon, D.L. Palmquist","Selenium content of foods grown or sold in Ohio",1980,"Ohio Report","65","1","",""
"D3766 ","V Chaudhary, F Weber","Barley bran flour evaluated as dietary fiber ingredient in wheat bread",1990,"Cereal Foods World","35","6","560","562"
"D3899 ","A Homnava, W Rogers, R R Eitenmiller","Provitamin A activity of specialty fruit marketed in the United States.",1990,"J. Food Composition and Analysis","3","","119","133"
"D3933 ","C. Y. Lee, R.W. Robinson","Influence of the crimson gene (ogc) on vitamin A content of tomato",1980,"Horticultural Science","15","","260","261"
"D4072 ","C. Bolton-Smith, R.J.G. Price, Steven T. Fenton, Dominic J. Harrington, M.J. Shearer","Compilation of a provisional UK database for the phylloquinone (vitamin K) content of foods",2000,"British Journal of Nutrition","83","","389","399"
"D4073 ","E. Jakob, I. Elmadfa","Rapid and simple HPLC analysis of vitamin K in food, tissues and blood",2000,"Food Chemistry","68","","219","221"
"D4701 ","M. Murkovic","Development of an Austrian carotenoid database",2000,"Journal of Food Composition and Analysis","13","","435","440"
"D4743 ","J.K. Daun, R. Przybylski","Environmental effects on the composition of four Canadian flax cultivars",2000,"Proceedings of the 58th Meeting of the Flax Institute of the United States","","","80","91"
"S1141 ","Produce Marketing Association (PMA)","Nutrient Content of Blueberry",1990,"","","","",""
"D4861 ","I.P. Ting","Chia: a potential oil crop for arid zones",1990,"New Industrial Crops and Products","","","197","200"
"D4901 ","J.I. Rader, C. M. Weaver, G. Angyal","Total folate in enriched cereal grain products in the United States following fortification",2000,"Food Chemistry","70","","275","289"
"D5202 ","V Chaudhary, F Weber","Dietary fiber ingredients obtained by processing brewer's dried grain",1990,"Journal of Food Science","55","2","551","553"
"D566  ","J. Leichtev, R. J. Bandoni","Nutrient Content of Mushrooms Grown in British Columbia",1980,"Canadian Institute of Food Technology Journal","13","3","122",""
"D5861 ","B. Pedersen, K.E.B. Knudsen, B.O. Eggum","The nutritive value of amaranth grain (Amaranthus caudatus): Energy and fibre of raw and processed grain",1990,"Plant Food for Human Nutrition","40","","61","71"
"D739  ","J.H. Hankin, S. Margen, N. Goldsmith","Contribution of Hard Water to Calcium and Magnesium Intakes of Adults",1970,"Journal of the American Dietetic Association","56","3","212","224"
"S1023 ","Produce Marketing Association (PMA)","Nutrient Content of Banana",1990,"","","","",""
"S1183 ","Produce Marketing Association (PMA)","Nutrient Content of Apple",1990,"","","","",""
"S1341 ","California Prune Board","Carotenoid Analysis of Prunes",2000,"","","","",""
"S14   ","National Cattlemen's Beef Association (NCBA)","Nutrient Content of Ground Beef",2000,"","Chicago","IL","",""
"S1742 ","Nutrient Data Laboratory, ARS, USDA","National Food and Nutrient Analysis Program - Industrial Flour",2000,"","Beltsville","MD","",""
"S1821 ","Utah State University","Composition of Foods",1980,"","","","",""
"S2    ","National Cattlemen's Beef Association (NCBA)","Nutrient Content of Retail Beef Cuts with 1/8 inch Trim Beef",2000,"","Chicago","IL","",""
"S22   ","Nutrient Data Laboratory, ARS, USDA","National Food and Nutrient Analysis Program Wave 3a",2000,"","Beltsville","MD","",""
"S23   ","Nutrient Data Laboratory, ARS, USDA","National Food and Nutrient Analysis Program Wave 3b",2000,"","Beltsville","MD","",""
"S2381 ","Nutrient Data Laboratory, ARS, USDA","American Indian/Alaskan Native Database - Navajo Foods 1999-2000",2000,"","Beltsville","MD","",""
"S2621 ","California Salmon Council","Nutrient Analysis of King Salmon Samples Caught off of the California Coast",2000,"","Folsom","CA","",""
"S2682 ","Food and Drug Administration (FDA), DHHS","FDA Total Diet Study",2000,"","","","",""
"S3    ","University of Wisconsin - Madison, Muscle Biology Laboratory","Nutrient Content of Alternate Red Meat Products",2000,"","Madison","WI","",""
"S53   ","Produce Marketing Association (PMA)","Nutrient Content of Sweet Cherries",1990,"","","","",""
"S561  ","Nutrient Data Laboratory, ARS, USDA","National Food and Nutrient Analysis Program Wave 5b",2000,"","Beltsville","MD","",""
"S562  ","Nutrient Data Laboratory, ARS, USDA","National Food and Nutrient Analysis Program Wave 4f",2000,"","Beltsville","MD","",""
"S74   ","Food and Drug Administration (FDA), DHHS","FDA Total Diet Study",1990,"","","","",""
"S82   ","Nutrient Data Laboratory, ARS, USDA","Determination of the Tocopherol Content of Selected Foods",1990,"","Beltsville","MD","",""
"S961  ","National Sunflower Association","Nutrient Analysis of Oil Roasted Sunflower Seeds",2000,"","Bismark","ND","",""
"S963  ","Produce Marketing Association (PMA)","Nutrient Content of Raspberries",1990,"","","","",""
