Section 14
------------------------------------------------
	
			Normalization :-
----------------------------------------------------

-  NORMALIZATION IS THE PROCESS OF ORGANIZING DATA TO MINIMUM DATA REDUNDANCY (DATA DUPLICATION).

    DATA REDUNDANCY :-
	    - DISK SPACE WASTAGES.
		- DATA INCONSISTENCY .
		- DML QUERY BECOME SLOW.
		
 1) 1NF (FIRST NORMAL FORM) :-

   - THA DATA IN EACH COLUMN SHOULD BE AUTOMIC (NO MULTIPLE VALUES SEPRATED BY COLUMN).
   - TABLES DOES NOT CONTAIN ANY REPEATING COLUMN GROUPS.
   - IDENTITY EACH RECORD UNIQUELY USING PRIMARY KEY.

  2) 2NF(SECOND NORMAL FORM) :-
  
  - TABLE MEET ALL THE CONDITION OF 1NF.
  - MOVE REDUNDANT DATA TO A SEPRATE TABLES.
  - CREATE RELATIONSHIP BETWEEN THESE TABLE USING FOREIGN KEY.
  
  3)3NF(THIRD NORMAL FORM) :-
  
  - MEET ALL THE CONDITION OF 1NF AND 2NF.
  - DOES NOT CONTAIN COLUMN (ATTRIBUTE) THAT ARE NOT FULLY DEPENDENT UPON THE PRIMARY KEY.


  
   
 
								